### ISSUE TITLE
区块链的数据存储现在可以破解、修改吗？如果成功，对现有社区有什么影响?

### ISSUE THREAD

**Issue by dako40** [TaibiaoGuo/blockchain101#11]
区块链的数据存储现在可以破解、修改吗？那区块链未来有没有可能被破解的危险？可不可能，通过区块链的破解，来由现实获得不法利益？
                                                                                                                                       璇233

**Comment by OnlineCourseOnly** [comment]
这个问题建议归并到
***Duplicate of #9***
> 区块链的安全性问题是什么样的，比如量子计算这些如何威胁到区块链的安全。

忌078
