### ISSUE TITLE
比特币和区块链

### ISSUE THREAD

**Issue by Mhhhhs** [TaibiaoGuo/blockchain101#57]
比特币和区块链有什么关系？
萌075

**Comment by GuoxingLuo0902** [comment]
中本聪的论文里没有提及区块链，只是把数据结构用一些词来解释和定义。数据结构里有transaction，block，chain。后来者把整个体系拿出来，叫做blockchain。所以，比特币的底层设计思想，衍生出了blockchain这个词，后来者把bitcoin称为一种blockchain。偏题说说自己的理解。bitcoin牛逼的地方不在于技术，这些技术都存在很多年了，bitcoin牛逼的地方在于从经济的角度出来构建了一套系统，而这套系统包含了这些技术。所以本质上bitcoin牛逼之处的确在于巧妙的结合了这些技术，但牛逼之处也在于经济学与技术的完美结合。而后来的区块链系统，大多偏离了bitcoin的设计思路。比如很多blockchain系统纯粹称为了数据共享框架。
